### ISSUE TITLE
Stage 3 - Errors creating destination sources (various)

### ISSUE THREAD

**Issue by lcordero** [konveyor/pvc-migrate#128]
**== Error ==**
**Description:**
1) Container port should be Int instead of String.
2) Service/Route port and targetPort should be Int instead of String.

**Error:**
```
TASK [Create a pod for rsync] ****************************************************************************

    "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Pod in version \\\\\"v1\\\\\" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Ports: []v1.ContainerPort: v1.ContainerPort.ContainerPort: readUint32: unexpected character: \\\\ufffd, error found in #10 byte of ...|erPort\\\\\": \\\\\"22\\\\\", \\\\\"name|..., bigger context ...|nc-transfer:latest\\\\\", \\\\\"ports\\\\\": [{\\\\\"containerPort\\\\\": \\\\\"22\\\\\", \\\\\"name\\\\\": \\\\\"rsyncd\\\\\", \\\\\"protocol\\\\\": \\\\\"TCP\\\\\"}], \\\\\"volum|...\",\"reason\":\"BadRequest\",\"code\":400}\\n'",
    "reason": "Bad Request",
    "status": 400
}
```

**Possible solution:**
On file: _3_run_rsync/templates/pod.yml.j2_ and _3_run_rsync/templates/svc.yml.j2_ remove double quotes for containerPort values and add `| int` to ensure it'll be converted to Int.
```
# Pod Template
...
    ports:
    - containerPort: {{ rsyncd_port | int }}
      name: rsyncd
      protocol: TCP
...
    ports:
      - containerPort: {{ stunnel_port | int }}
        name: stunnel
        protocol: TCP
...

# Service/Route Template
...
  ports:
  - name: stunnel
    port: {{ stunnel_port | int }}
    protocol: TCP
    targetPort: {{ stunnel_port | int }}
...
  port:
    targetPort: {{ stunnel_port | int }}
```

I have tested both possible solutions with no issues.
